processes and signals

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -17,6 +17,7 @@ start() {
   fi
   nohup "${RELPATH}" &> /dev/null &
   echo "$!" >| "${PIDFILE}"
+  echo "${PROGRAM} ${MESSAGES['start']}"
 }
 
 stop() {
@@ -24,20 +25,24 @@ stop() {
     echo "${PROGRAM} is not running"
     exit 1
   fi
-  trap '
-    trap RETURN
-    rm -f -- "${PIDFILE}"
-  ' RETURN
   kill -- "$(< "${PIDFILE}")" 2> /dev/null
+  if [ $? -eq 0 ]; then
+    rm -f -- "${PIDFILE}"
+    echo "${PROGRAM} ${MESSAGES['stop']}"
+  else
+    echo "Failed to stop ${PROGRAM}"
+    exit 1
+  fi
 }
 
 restart() {
   stop
   start
+  echo "${PROGRAM} ${MESSAGES['restart']}"
 }
 
 if (( $# == 1 )) && [[ -v "MESSAGES[$1]" ]]; then
-  "$1" && printf '%s %s\n' "${PROGRAM}" "${MESSAGES[$1]}"
+  "$1"
 else
   printf 'Usage: %s {start|stop|restart}\n' "${PROGRAM}"
   exit 1
