processes and signals

diff --git a/processes_and_signals/manage_my_process b/processes_and_signals/manage_my_process
--- a/processes_and_signals/manage_my_process
+++ b/processes_and_signals/manage_my_process
@@ -1,6 +1,49 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# Script to manage daemon
 
-while true; do
-    echo "I am alive!" >> /tmp/my_process
-    sleep 2
-done
+PROGRAM='manage_my_process'
+RELPATH="$(dirname "$(readlink -f "$0")")/${PROGRAM}"
+PIDFILE="${PIDFILE:-/var/run/my_process.pid}"
+declare -A MESSAGES=( 
+  ['start']='started'
+  ['stop']='stopped'
+  ['restart']='restarted'
+)
+
+start() {
+  if [ -f "${PIDFILE}" ]; then
+    echo "${PROGRAM} is already running"
+    exit 1
+  fi
+  nohup "${RELPATH}" &> /dev/null &
+  echo "$!" >| "${PIDFILE}"
+  echo "${PROGRAM} ${MESSAGES['start']}"
+}
+
+stop() {
+  if [ ! -f "${PIDFILE}" ]; then
+    echo "${PROGRAM} is not running"
+    exit 1
+  fi
+  kill -- "$(< "${PIDFILE}")" 2> /dev/null
+  if [ $? -eq 0 ]; then
+    rm -f -- "${PIDFILE}"
+    echo "${PROGRAM} ${MESSAGES['stop']}"
+  else
+    echo "Failed to stop ${PROGRAM}"
+    exit 1
+  fi
+}
+
+restart() {
+  stop
+  start
+  echo "${PROGRAM} ${MESSAGES['restart']}"
+}
+
+if (( $# == 1 )) && [[ -v "MESSAGES[$1]" ]]; then
+  "$1"
+else
+  printf 'Usage: %s {start|stop|restart}\n' "${PROGRAM}"
+  exit 1
+fi
